config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  # get 'home/index'
  
  root "home#index"
  
  get 'home/about'

  post '/' => 'home#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

    belongs_to :user
    validates :ticker, presence: true
    validates :ticker, format: { without: /\s/ }
end

app/models/user.rb
class User < ApplicationRecord
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stocks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  
  def index
    @api = StockQuote::Stock.new(api_key: "pk_09440222b4794da68056a63c9781ed46")
    
    if params[:ticker] == ""
      @nothing = "You Enetred No Symbol !"
    elsif params[:ticker]
      @stock = StockQuote::Stock.quote(params[:ticker])
    end
  
  end

  def about
    
  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /stocks or /stocks.json
  def index
    @api = StockQuote::Stock.new(api_key: 'pk_16a849fd637243a79fff90fa4d42bc5d')
    @stocks = Stock.all
  end

  # GET /stocks/1 or /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks or /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully created." }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1 or /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to stock_url(@stock), notice: "Stock was successfully updated." }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1 or /stocks/1.json
  def destroy
    @stock.destroy

    respond_to do |format|
      format.html { redirect_to stocks_url, notice: "Stock was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @ticker = current_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<br/>
<% flash.each do |name, msg| %>
    <div class="alert alert-warning alert-dismissable" role="alert">
        <button class="close" data-dismiss="alert">
            <small><sup>x</sup></small>
        </button>
        <%= content_tag(:div, msg) %>
    </div>
<% end %>      

app/views/home/_footer.html.erb
<center> This is the Footer of Stock App </center>

<center> <strong> Copyrights (R) </strong> </center>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Stocking", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
    
    <li class="nav-item">
        <%= link_to "About Me", home_about_path, class:"nav-link" %>
    </li>


    <% if user_signed_in? %>
      
      <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Show Stocks", stocks_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Add Stock", new_stock_path, class:"nav-link" %>
      </li>

      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>

    <% else %>

      <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class:"nav-link" %>
      </li>


    <% end %>


    
      
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


app/views/home/about.html.erb
<h1> About Stocking App </h1>
<p> This is About page of of Stock Market App </p>

app/views/home/index.html.erb
<h1> Stocking </h1>
<p> This is Stock Market App </p>


<%= form_tag root_path, :method => 'POST' do %>
    <%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
    <%= submit_tag 'Lookup' %>
<% end %>

<br>

<% if @stock %>
    <h2>Comapny : <strong> <%= @stock.company_name %> </strong> </br>  
    <h5> Stock Price : $<%= @stock.latest_price %> </h5></h1>
<% elsif @nothing %>
    <%= @nothing %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock Market App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render 'home/navbar' %>
    
    <div class="container">

      <%= render 'home/flash' %>
      
      <br>
      <%= yield %>
    </div>

    <%= render 'home/footer' %>
  
    </body>
</html>

app/views/stocks/_form.html.erb
<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
        <% stock.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker %>
  </div>

  <div class="field">
    <% form.label :user_id %>
    <%= form.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<table class="table table-striped table-bordered table-hover">
<thead class="thead-dark">
  <tr>
    <th>Company</th>
    <th>Ticker</th>
    <th>Current Price</th>
    <th>Market Cap</th>
    <th colspan="2"></th>
  </tr>
</thead>

<tbody>
  <% @stocks.each do |stock| %>
    <% if stock.user_id == current_user.id %>
      
      <% @ticker = StockQuote::Stock.quote(@stock.ticker) %>
      <% if !@ticker %>
        <tr>
          <td><%= link_to "Error", stock %></td>
          <td><%= stock.ticker %></td>
          <td>N/A</td>
          <td>N/A</td>
          <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
          <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        </tr>
      <% else %>
        <tr>
          <td><%= link_to @ticker.company_name, stock %></td>
          <td><%= @ticker.symbol %></td>
          <td>$<%= number_with_precision(@ticker.latest_price, :precision => 2, :delimiter => ',') %></td>
          <td>$<%= number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ',') %></td>
          <td><center><%= link_to 'Edit', edit_stock_path(stock) %></center></td>
          <td><center><%= link_to 'Delete', stock, method: :delete, data: { confirm: 'Are you sure?' } %></center></td>
        </tr>
      
      <% end %>

    <% end %>
  <% end %>

</tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<% @ticker = StockQuote::Stock.quote(@stock.ticker) %>
      <% if !@ticker %>
         The ticker: <%= @stock.ticker %><br/> does not exist!
      <% else %>
        <% @logo = StockQuote::Stock.logo(@stock.ticker)%>
        <img src="<%= @logo.url %>"><br/><br/>

          <h2><%= @ticker.company_name %></h2><br/>
          Ticker Symbol: <%= @ticker.symbol %><br/>
          Current Price: $<%= number_with_precision(@ticker.latest_price, :precision => 2, :delimiter => ',') %><br/>

          Previous Close: $<%= number_with_precision(@ticker.previous_close, :precision => 2, :delimiter => ',') %><br/>

          Percent Change: <%= @ticker.change_percent %>%<br/>

          YTD Change: <%= number_with_precision(@ticker.ytd_change, :precision => 2, :delimiter => ',') %>%<br/>
	                    
          Market Cap: $<%= number_with_precision(@ticker.market_cap, :precision => 2, :delimiter => ',') %><br/>
      
      <% end %>


<br/><br/>
<%= link_to 'Edit', edit_stock_path(@stock), class:"btn btn-outline-dark" %> 
<%= link_to 'Back', stocks_path, class:"btn btn-outline-dark" %>